# Generated by Django 3.1 on 2020-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dan', '0002_post_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
