# Generated by Django 3.1 on 2020-09-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200909_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myInfo',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
