# Generated by Django 3.1 on 2020-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_myinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myInfo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
