# Generated by Django 3.1 on 2020-09-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200909_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='red.jpg', upload_to='profile/image'),
        ),
    ]
