# Generated by Django 3.1 on 2020-09-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_borad'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='profileImage',
            field=models.ImageField(default='red.jpg', upload_to='post_images'),
        ),
    ]
